<x-app-layout>

</x-app-layout>


<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    @include("admin.admincss")
  </head>
  <body>
    
    <div class="container-scroller">
        @include("admin.navbar")
        
        
        <table class="table table-hover">
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Action</th>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          <tr>
            <td>1</td>
            <td>Admin</td>
            <td>admin@gmail.com</td>
            <td>Delete</td>
          </tr>
          
        </table>

    </div>
    
    <!-- container-scroller -->
    @include("admin.adminscript")
  </body>
</html>